import { globSync } from "glob";
import { rmSync } from "node:fs";
import configurations from "./configLoader";
import ImageWorker from "./lib/core/image";
import ImageSetGenerator from "./lib/core/imageset";
import VideoWorker from "./lib/core/video";
import WebDocsWorker from "./lib/core/webdocs";
import {
	ConfigurationOptions,
	ImageWorkerOutputTypes,
	ImageWorkerParamsMain,
	VideoWorkerParamsMain,
} from "./lib/types";
import { copyFiles } from "./lib/utils";

export class Minomax {
	configurations: ConfigurationOptions;
	#videoWorker: VideoWorker;
	#imageWorker: ImageWorker;
	#imageGenerator: ImageSetGenerator;
	#webDocWorker: WebDocsWorker;

	constructor() {
		this.configurations = configurations();
		this.#videoWorker = new VideoWorker(this.configurations);
		this.#imageWorker = new ImageWorker(this.configurations);
		this.#imageGenerator = new ImageSetGenerator(this.configurations);
		this.#webDocWorker = new WebDocsWorker(this.configurations);
	}

	async minomax({
		imageWorkerParams,
		videoWorkerParams,
		destinationBasePath = this.configurations.destPath,
		ignorePatterns = this.configurations.ignorePatterns,
		webDocFilesPatterns = this.configurations.webdoc.lookupPatterns,
		removeOld = this.configurations.removeOld,
	}: {
		imageWorkerParams: ImageWorkerParamsMain;
		videoWorkerParams: VideoWorkerParamsMain;
		destinationBasePath?: string;
		ignorePatterns?: string[];
		webDocFilesPatterns?: string[];
		removeOld?: boolean;
	}) {
		ignorePatterns = [
			...ignorePatterns,
			"node_modules/**",
			`${destinationBasePath}/**`,
		];

		// Step:1 Pre processing
		/*  I-Delete old dest */
		if (removeOld) {
			rmSync(destinationBasePath, { force: true, recursive: true });
		}

		/* II- Copy webdoc files to dest path */
		const webDocFiles: string[] = globSync(webDocFilesPatterns, {
			ignore: ignorePatterns,
			absolute: true,
		});
		await copyFiles(webDocFiles, destinationBasePath);

		// Step:2  I) Image set generation , II) Img tag transformation, III) Video thumbnail linking.
		const htmlPathPatterns: string[] = [...webDocFilesPatterns].filter(
			(pattern: string) => pattern.endsWith(".html"),
		);
		await this.#imageGenerator.generate(
			htmlPathPatterns,
			destinationBasePath,
			ignorePatterns,
		);

		// Step:3 Image worker - compress images that was generated by previous worker.
		/* I) Standard pictures */
		const { targetFormat } = imageWorkerParams;
		const imagePaths: string[] = globSync(
			this.configurations.imagePatterns,
			{
				ignore: ignorePatterns,
				cwd: destinationBasePath, //taking only generated images
				absolute: true,
			},
		);
		const compressedImagesDestination: string = process.cwd(); //overwriting uncompressed images with compressed
		await this.#imageWorker.encode(
			imagePaths,
			targetFormat,
			compressedImagesDestination,
		);

		/* II) SVG images */
		const svgFiles: string[] = globSync(["**/*.svg"], {
			ignore: ignorePatterns,
			cwd: destinationBasePath, //taking only generated images
			absolute: true,
		});
		await this.#imageWorker.encode(
			svgFiles,
			"svg",
			compressedImagesDestination,
		);

		// Step:4 Video worker - I) Compress videos, II) Generate thumbnail of them.
		const { codecType, encodeLevel } = videoWorkerParams;
		const videoEncodeLevel: 1 | 2 | 3 = encodeLevel || 3;
		const thumbnailSeekPercent: number = 15;

		const videoPaths: string[] = globSync(
			this.configurations.videoLookupPatterns,
			{
				ignore: ignorePatterns,
				absolute: true,
			},
		);
		await this.#videoWorker.encode(
			videoPaths,
			codecType,
			videoEncodeLevel,
			thumbnailSeekPercent,
			destinationBasePath,
		);

		// Step:5 Webdoc worker - minify HTML, JS & CSS
		const fileSearchBasePath: string = destinationBasePath;
		const minifiedWebDocsDestination: string = process.cwd(); //overwriting non-minified with minified files
		await this.#webDocWorker.uglify({
			webDocFilesPatterns: webDocFilesPatterns,
			destinationBase: minifiedWebDocsDestination,
			fileSearchBasePath: fileSearchBasePath,
			noDirPatterns: ignorePatterns,
		});
	}

	async compressImages({
		targetFormat = "webp",
		pathPatterns = this.configurations.imagePatterns,
		destinationBasePath = this.configurations.destPath,
		ignorePatterns = this.configurations.ignorePatterns,
	}: {
		targetFormat?: ImageWorkerOutputTypes;
		pathPatterns?: string[];
		destinationBasePath?: string;
		ignorePatterns?: string[];
	}) {
		ignorePatterns = [
			...ignorePatterns,
			"node_modules/**",
			`${destinationBasePath}/**`,
		];

		const imagesFiles: string[] = globSync(pathPatterns, {
			ignore: ignorePatterns,
			absolute: true,
		});

		try {
			await this.#imageWorker.encode(
				imagesFiles,
				targetFormat,
				destinationBasePath,
			);
		} catch (err) {
			console.log(err);
			process.exit(1);
		}
	}

	async compressVideos({
		codecType = "mav1",
		pathPatterns = this.configurations.videoLookupPatterns,
		encodeLevel = 3,
		destinationBasePath = this.configurations.destPath,
		ignorePatterns = this.configurations.ignorePatterns,
	}: {
		codecType?: "wav1" | "mav1" | "mx265";
		pathPatterns?: string[];
		encodeLevel?: 1 | 2 | 3;
		destinationBasePath?: string;
		ignorePatterns?: string[];
	}) {
		ignorePatterns = [
			...ignorePatterns,
			"node_modules/**",
			`${destinationBasePath}/**`,
		];

		const videoFiles: string[] = globSync(pathPatterns, {
			ignore: ignorePatterns,
			absolute: true,
		});

		try {
			const thumbnailSeekPercent: number = 20;
			await this.#videoWorker.encode(
				videoFiles,
				codecType,
				encodeLevel,
				thumbnailSeekPercent,
				destinationBasePath,
			);
		} catch (err) {
			console.log(err);
			process.exit(1);
		}
	}

	async minifyWebdoc({
		pathPatterns = this.configurations.webdoc.lookupPatterns,
		destinationBasePath = this.configurations.destPath,
		fileSearchBasePath = process.cwd(),
		ignorePatterns = this.configurations.ignorePatterns,
	}: {
		pathPatterns?: string[];
		destinationBasePath?: string;
		fileSearchBasePath?: string;
		ignorePatterns?: string[];
	}) {
		ignorePatterns = [
			...ignorePatterns,
			"node_modules/**",
			`${destinationBasePath}/**`,
		];

		try {
			await this.#webDocWorker.uglify({
				webDocFilesPatterns: pathPatterns,
				destinationBase: destinationBasePath,
				fileSearchBasePath: fileSearchBasePath,
				noDirPatterns: ignorePatterns,
			});
		} catch (err) {
			console.log(err);
			process.exit(1);
		}
	}

	async generateImageSets({
		pathPatterns = this.configurations.imagePatterns,
		destinationBasePath = this.configurations.destPath,
		ignorePatterns = this.configurations.ignorePatterns,
	}: {
		pathPatterns?: string[];
		destinationBasePath?: string;
		ignorePatterns?: string[];
	}) {
		ignorePatterns = [
			...ignorePatterns,
			"node_modules/**",
			`${destinationBasePath}/**`,
		];

		try {
			await this.#imageGenerator.generate(
				pathPatterns,
				destinationBasePath,
				ignorePatterns,
			);
		} catch (err) {
			console.log(err);
			process.exit(1);
		}
	}
}

export type minomaxOptions = ConfigurationOptions;
